### Pandas DataFrame Manipulation

#### DataFrame manipulation in Pandas involves editing and modifying existing DataFrames. Some common DataFrame manipulation operations are:

1. Adding rows/columns
2. Removing rows/columns
3. Renaming columns


### Add a New Column to a Pandas DataFrame
#### We can add a new column to an existing Pandas DataFrame by simply declaring a new list as a column.

In [11]:
import pandas as pd

# define a dictionary containing student data
data = {'Name': ['John', 'Emma', 'Michael', 'Sophia'],
        'Height': [5.5, 6.0, 5.8, 5.3],
        'Qualification': ['BSc', 'BBA', 'MBA', 'BSc']}

# convert the dictionary into a DataFrame
df = pd.DataFrame(data)

# declare a new list (first step)
address = ["India","Russia","China",""]
#
df['Height'] = address

df

      Name  Height Qualification
0     John   India           BSc
1     Emma  Russia           BBA
2  Michael   China           MBA
3   Sophia                   BSc

### Add a New Row to a Pandas DataFrame
#### Adding rows to a DataFrame is not quite as straightforward as adding columns in Pandas. We use the `.loc` property to add a new row to a Pandas DataFrame.

In [10]:
import pandas as pd

# define a dictionary containing student data
data = {'Name': ['John', 'Emma', 'Michael', 'Sophia'],
        'Height': [5.5, 6.0, 5.8, 5.3],
        'Qualification': ['BSc', 'BBA', 'MBA', 'BSc']}

# convert the dictionary into a DataFrame
df = pd.DataFrame(data)


df.loc[2] = ['Sahil', 5.0, 'LLM']
#
df

     Name  Height Qualification
0    John     5.5           BSc
1    Emma     6.0           BBA
2   Sahil     5.0           LLM
3  Sophia     5.3           BSc

### Remove Rows/Columns from a Pandas DataFrame
#### We can use `drop()` to delete rows and columns from a DataFrame.

#### Remove Rows

In [24]:
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Felipe', 'Rita'],
        'Age': [25, 30, 35, 40, 22, 29],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Bogota', 'Bangalore']}


# delete row with index 4
df.drop(2, axis=0, inplace=True) # index, axis, inplace

# delete rows with index 1 and 3

dropping_list = [1,3]
df.drop(dropping_list, axis=0, inplace=True)

#### Remove Columns

In [17]:
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Felipe', 'Rita'],
        'Age': [25, 30, 35, 40, 22, 29],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Bogota', 'Banglore']}

df = pd.DataFrame(data)

# Drop a single column

df.drop(columns='City', inplace=True)
df.drop('Name', axis = 1, inplace=True)
#
# #
# # # Drop multiple columns
dropping_cols = ['Name', 'Age']
df.drop(columns=dropping_cols, inplace=True)
df.drop(dropping_cols, axis=1, inplace=True)

df

       City
0  New York
1    London
2     Paris
3     Tokyo
4    Bogota
5  Banglore

### Rename Labels in a DataFrame
#### We can rename columns in a Pandas DataFrame using the rename() function.

In [27]:
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'London', 'Paris', 'Tokyo']}

# predicate pushdown and projection pushdown

df = pd.DataFrame(data)

rename_dict = {'Name': 'First_Name',
               'Age': 'Age_In_Years',
               'City': 'City_Name'}

# rename columns 'Age' and 'Name'
df.rename(rename_dict, axis=1, inplace=True)


df

  First_Name  Age_In_Years City_Name
0      Alice            25  New York
1        Bob            30    London
2    Charlie            35     Paris
3      David            40     Tokyo

### Pandas Handling Duplicate Values

- In large datasets, we often encounter duplicate entries in tables. These duplicate entries can throw off our analysis and skew the results.
- Pandas provides several methods to find and remove duplicate entries in DataFrames.


### Find Duplicate Entries

- We can find duplicate entries in a DataFrame using the duplicated() method. It returns True if a row is duplicated and returns False otherwise.

In [28]:
data = {
    'Name': ['John', 'Anna', 'John', 'Anna', 'John'],
    'Age': [28, 24, 28, 24, 28],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

df

   Name  Age         City
0  John   28     New York
1  Anna   24  Los Angeles
2  John   28     New York
3  Anna   24  Los Angeles
4  John   28      Chicago

In [30]:
import pandas as pd

# create dataframe
data = {
    'Name': ['John', 'Anna', 'John', 'Anna', 'John'],
    'Age': [28, 24, 28, 24, 28],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)


# check for duplicate entries
# df.duplicated()

# check for duplicate entries in columns Name and Age
df.duplicated(subset=['Name', 'Age'])

0    False
1    False
2     True
3     True
4     True
dtype: bool

### Remove Duplicate Entries
- We can remove duplicate entries in Pandas using the drop_duplicates() method.

In [32]:
import pandas as pd

# create dataframe
data = {
    'Name': ['John', 'Anna', 'John', 'Anna', 'John'],
    'Age': [28, 24, 28, 24, 19],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

# remove duplicates
df.drop_duplicates(inplace=True, keep="last") #keep=last

df

   Name  Age         City
2  John   28     New York
3  Anna   24  Los Angeles
4  John   19      Chicago

### Practice Test
1. Add a new column called "`DiscountedAmount`" that is OrderAmount minus 10% discount.
2. Remove the "`Name`" column from the DataFrame.
3. Drop duplicate entries based on the "`CustomerID`" column (keep the first occurrence only).

In [ ]:
import pandas as pd

data = {
    'CustomerID': [101, 102, 103, 101, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'David'],
    'OrderAmount': [250, 450, 300, 250, 500]
}

df = pd.DataFrame(data)

### Problem 1: Creating a DataFrame

Task: Create a DataFrame with the following data:


`data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [24, 30, 35, 40],
        'City': ['New York', 'Toronto', 'London', 'Sydney']}`

Goal: Display the created DataFrame.
### Problem 2: Basic DataFrame Operations

1. Display only the Name and City columns.
2. Select and print the rows where Age is greater than 30.

### Problem 3: Adding and Deleting Columns

1. Add a new column named Salary with values [70000, 80000, 120000, 95000].
2. Delete the City column.
3. Goal: Display the updated DataFrame.

In [33]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [124, 30, 35, 401],
    'City': ['New York', 'Sydney', 'London', 'Tokyo']
}

df = pd.DataFrame(data)

df

      Name  Age      City
0    Alice  124  New York
1      Bob   30    Sydney
2  Charlie   35    London
3    David  401     Tokyo

In [35]:
column_display = ['Name', 'City']
df[['Name', 'City']]

      Name      City
0    Alice  New York
1      Bob    Sydney
2  Charlie    London
3    David     Tokyo

In [39]:
df['Age'] > 30

0     True
1    False
2     True
3     True
Name: Age, dtype: bool

In [40]:
df[df['Age'] > 30]

      Name  Age      City
0    Alice  124  New York
2  Charlie   35    London
3    David  401     Tokyo

In [41]:
df['salary'] = [1,3,4,56]
df

      Name  Age      City  salary
0    Alice  124  New York       1
1      Bob   30    Sydney       3
2  Charlie   35    London       4
3    David  401     Tokyo      56

In [42]:
df.drop(columns='City', inplace=True)

df

      Name  Age  salary
0    Alice  124       1
1      Bob   30       3
2  Charlie   35       4
3    David  401      56