### Pandas CSV
- Pandas provides functions for both reading from and writing to CSV files.
- CSV stands for Comma-Separated Values. It is a popular file format used for storing tabular data, where each row represents a record, and columns are separated by a delimiter (generally a comma).


### Read CSV Files
- In Pandas, the `read_csv()` function allows us to read data from a CSV file into a DataFrame. It automatically detects commas and parses the data into appropriate columns.

In [7]:
import pandas as pd

# read csv file

df = pd.read_csv("/Users/sahilnagpal/Desktop/Pragra-Python/data/myfile.csv",
                 sep='|',
                 usecols = ['Name','Age'])

df.head(5)

   Name  Age
0  John   25
1  Jane   24
2  Jill   23

### `read_csv()` Syntax

The syntax of read_csv() in Pandas is:

In [ ]:
df = pd.read_csv(
    #filepath_or_buffer,
    #sep='',
    #header=0,
    # names=['EmployeeID','FirstName','LastName','Department','Position','Salary'],
    # index_col='EmployeeID',
    # usecols=['EmployeeID', 'Position'],
    # skiprows=[1, 3],
    # nrows=100,
    # skipinitialspace=True
)

- `filepath_or_buffer`: represents the path or buffer object containing the CSV data to be read
- `sep(optional)`: specifies the delimiter used in the CSV file
- `header(optional)`: indicates the row number to be used as the header or column names
- `names(optional)`: a list of column names to assign to the DataFrame
- `index_col(optional)`: specifies the column to be used as the index of the DataFrame
- `usecols(optional)`: a list of columns to be read and included in the DataFrame
- `skiprows(optional)`: used to skip specific rows while reading the CSV file
- `nrows(optional)`: sets the maximum number of rows to be read from the CSV file
- `skipinitialspace(optional)`: determines whether to skip any whitespace after the delimiter in each field


These are some commonly used arguments of the `read_csv()` function. All of them are optional except `filepath_or_buffer`. There are many other optional arguments of read_csv().

### `read_csv()` With Arguments

In [ ]:
import pandas as pd

# read csv file with some arguments
df = pd.read_csv('/data/employee.csv', header=None, names=['col1', 'col2', 'col3'], skiprows=2)

df

### Write to CSV Files
- Pandas also provides the `to_csv()` function to write data from a DataFrame into a CSV file.

In [8]:
df

   Name  Age
0  John   25
1  Jane   24
2  Jill   23

In [3]:
import pandas as pd

# create a dictionary
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}

# create a dataframe from the dictionary
df = pd.DataFrame(data)



# write dataframe to csv file
df.to_csv('/Users/sahilnagpal/Desktop/Pragra-Python/data/output2.csv',sep='|',index=False,header=False)

### `to_csv()` Syntax

- The syntax of `to_csv()` in Pandas is:

In [ ]:
df.to_csv(
    # path_or_buf,
    sep=',',
    header=True,
    index=False,
    mode='r',
    encoding=None,
    quoting=None,
    line_terminator='\n',
)

- `path_or_buf`: represents the path or buffer object where the DataFrame will be saved as a CSV file
- `sep(optional)`: specifies the delimiter to be used in the output CSV file
- `header(optional)`: indicates whether to include the header row in the output CSV file
- `index(optional)`: determines whether to include the index column in the output CSV file
- `mode(optional)`: specifies the mode in which the output file will be opened
- `encoding(optional)`: sets the character encoding to be used when writing the CSV file
- `quoting(optional)`: determines the quoting behavior for fields that contain special characters
- `line_terminator(optional)`: specifies the character sequence used to terminate lines in the output CSV file

# 📦 Warehouse Inventory Analysis

You are working for a logistics company that manages multiple warehouses across the country.
You are given a CSV file named `inventory.csv` containing information about products stored in different warehouses.

---

## 📁 Dataset Columns

| Column Name      | Description                                     |
|------------------|-------------------------------------------------|
| WarehouseID      | Unique ID for each warehouse                    |
| WarehouseCity    | City where the warehouse is located             |
| Product          | Name of the product stored                      |
| Quantity         | Number of units of the product                  |
| UnitPrice        | Price per unit of the product                   |

---

## ✅ Tasks

1. **Read the dataset**
   - Load the file `inventory.csv` into a pandas DataFrame.

2. **Aggregation**
   - Calculate the **total inventory value** for each warehouse.
     *(Hint: inventory value = Quantity × UnitPrice)*
   - Find the **total quantity of each product** across all warehouses.
   - Identify the **warehouse with the highest total inventory value**.

3. **Save Results**
   - Save the aggregated product quantity table to a new CSV file named `product_totals.csv`.
   - Save the warehouse total value table to a new CSV file named `warehouse_values.csv`.

---

## 🎯 Bonus (Optional)
- Group the data by `WarehouseCity` and calculate the average inventory value per product.

---

## 🔍 Notes
- Use `pandas.read_csv()` to load data.
- Use `DataFrame.to_csv()` to save results.
- Display your final results in the notebook as well.