### Pandas Select

- Pandas select refers to the process of extracting specific portions of data from a DataFrame.
- Data selection involves choosing specific rows and columns based on labels, positions, or conditions.
- Pandas provides various methods, such as basic indexing, slicing, boolean indexing, and querying, to efficiently extract, filter, and transform data, enabling users to focus on relevant information for analysis and decision-making.

In [1]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [22, 28, 35, 19, 29],
    "City": ["New York", "Chicago", "New York", "Boston", "Chicago"],
    "Stream": ["Math", "Science", "Math", "Arts", "Science"],
    "Score": [85, 92, 78, 95, 88],
    "Sales_Q1": [10, 15, 8, 12, 14],
    "Sales_Q2": [12, 18, 9, 11, 15]
}

df = pd.DataFrame(data)

df

      Name  Age      City   Stream  Score  Sales_Q1  Sales_Q2
0    Alice   22  New York     Math     85        10        12
1      Bob   28   Chicago  Science     92        15        18
2  Charlie   35  New York     Math     78         8         9
3    David   19    Boston     Arts     95        12        11
4      Eva   29   Chicago  Science     88        14        15

1. Basic Selection Using .loc[]

The first argument of .loc[] filters rows based on a boolean condition, while the second argument selects the columns you want to keep

In [2]:
result_basic = df.loc[df["Age"] > 25, ["Name", "City"]]

result_basic

      Name      City
1      Bob   Chicago
2  Charlie  New York
4      Eva   Chicago

In [ ]:
# loc[row,column]

In [4]:
df

      Name  Age      City   Stream  Score  Sales_Q1  Sales_Q2
0    Alice   22  New York     Math     85        10        12
1      Bob   28   Chicago  Science     92        15        18
2  Charlie   35  New York     Math     78         8         9
3    David   19    Boston     Arts     95        12        11
4      Eva   29   Chicago  Science     88        14        15

2. Common Row Filtering Conditions

Comparison Operators: Use >, <, ==, !=, >=, <=.Membership (isin) Select rows where values match any item in a list.

In [3]:
df.loc[df['Stream'].isin(['Math', 'Science']),'Name']

0      Alice
1        Bob
2    Charlie
4        Eva
Name: Name, dtype: object

Multiple Conditions: Combine conditions using & (AND), | (OR), and ~ (NOT). Always use parentheses around each condition.

In [5]:
df.loc[(df['Age'] > 20) | (df['Score'] < 90)]

# and , or
# and --> &
# or --> |

      Name  Age      City   Stream  Score  Sales_Q1  Sales_Q2
0    Alice   22  New York     Math     85        10        12
1      Bob   28   Chicago  Science     92        15        18
2  Charlie   35  New York     Math     78         8         9
4      Eva   29   Chicago  Science     88        14        15

3. Dynamic Column Selection

You can also select columns based on conditions, such as their names or the data they contain
- By Name Pattern: Use the filter() method to select columns that match a substring or regex.

In [11]:
# By Name Pattern
df.filter(like='a')

      Name   Stream  Sales_Q1  Sales_Q2
0    Alice     Math        10        12
1      Bob  Science        15        18
2  Charlie     Math         8         9
3    David     Arts        12        11
4      Eva  Science        14        15

4. Alternative Methods Boolean Indexing

- For row filtering only, you can use df[df['Age'] > 25].
- Query Method: Use the query() method for a cleaner, SQL-like string syntax.

In [12]:
df.query('Age > 25 & City == "New York"')

      Name  Age      City Stream  Score  Sales_Q1  Sales_Q2
2  Charlie   35  New York   Math     78         8         9