### Pandas Dataframe Index
- Index in pandas dataframe act as reference for each row in dataset.
- It can be numeric or based on specific column values.
- The default index is usually a RangeIndex starting from 0, but you can customize it for better data understanding.

In [ ]:
#     Name    Age      City
# 0   John     25  New York
# 1  Alice     28    London
# 2    Bob     32     Paris

### Create Indexes in Pandas
#### Pandas offers several ways to create indexes. Some common methods are as follows:

1. Default Index
2. Setting Index
3. Creating a Range Index

### Default Index

- When we create a DataFrame or Series without specifying an index explicitly, Pandas assigns a default integer index starting from 0. For example,

In [2]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 28, 32],
        'City': ['New York', 'London', 'Paris']}



df = pd.DataFrame(data)
df

    Name  Age      City
0   John   25  New York
1  Alice   28    London
2    Bob   32     Paris

### Setting Index

- We can set an existing column as the index using the `set_index()` method. For example,

In [6]:
import pandas as pd

# create dataframe
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 28, 32],
        'City': ['New York', 'London', 'Paris']}

df = pd.DataFrame(data)


# set the 'Name' column as index
df.set_index('Age', inplace=True)

df

      Name      City
Age
25    John  New York
28   Alice    London
32     Bob     Paris

In [ ]:
import pandas as pd

# create dataframe
data = {'Name': ['John', 'Alice', 'Bob', 'Niharika'],
        'Age': [25, 28, 32, 25],
        'City': ['New York', 'London', 'Paris', 'Cuttack']}

df = pd.DataFrame(data)


# set the 'Name' column as index
df.set_index('Age', inplace=True)

df

### Creating a Range Index

- We can create a range index with specific start and end values using the `RangeIndex()` function. For example,

In [9]:
import pandas as pd

# create dataframe
data = {'Name': ['John', 'John', 'Bob'],
        'Phone_Number': [25, 25, 32],
        'Phone_Number_2': [25, 25, 32]}



# df = pd.DataFrame(data)

# create a range index
df = pd.DataFrame(data, index=pd.RangeIndex(101,104, name='IndexValues')) # startvalue , endvalue, name

df

             Name  Phone_Number  Phone_Number_2
IndexValues
101          John            25              25
102          John            25              25
103           Bob            32              32

### Modifying Indexes in Pandas
- Pandas allows us to make changes to indexes easily. Some common modification operations are:

1. Renaming Index
2. Resetting Index

### Renaming Index
- We can rename an index using the `rename()` method.

In [13]:
import pandas as pd

# create a dataframe
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 28, 32],
        'City': ['New York', 'London', 'Paris']}


df = pd.DataFrame(data)



# rename index
renameIndex = {0: '0_index', 1: 'first_index', 2: 'second_index'}
df.rename(index=renameIndex, inplace=True)

# display dataframe after index is renamed
# print('Modified DataFrame')
df

               Name  Age      City
0_index        John   25  New York
first_index   Alice   28    London
second_index    Bob   32     Paris

### Resetting Index

- We can reset the index to the default integer index using the reset_index() method.

In [17]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 28, 32],
        'City': ['New York', 'London', 'Paris']}

# create a dataframe
df = pd.DataFrame(data)

# rename index
df.rename(index={0: 'A', 1: 'B', 2: 'C'}, inplace=True)


# display dataframe

# reset index
df.reset_index(inplace=True)

# display dataframe after index is reset

df

  index   Name  Age      City
0     A   John   25  New York
1     B  Alice   28    London
2     C    Bob   32     Paris

### Access Rows by Index
- We can access rows of a DataFrame using the .iloc property.

In [18]:
import pandas as pd

# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
                               'Mahindra', 'Maruti', 'Hyundai',
                               'Renault', 'Tata', 'Maruti'],
                     'Year': [2012, 2014, 2011, 2015, 2012,
                              2016, 2014, 2018, 2019],
                     'Kms Driven': [50000, 30000, 60000,
                                    25000, 10000, 46000,
                                    31000, 15000, 12000],
                     'City': ['Gurgaon', 'Delhi', 'Mumbai',
                              'Delhi', 'Mumbai', 'Delhi',
                              'Mumbai', 'Chennai',  'Ghaziabad'],
                     'Mileage':  [28, 27, 25, 26, 28,
                                  29, 24, 21, 24]})

data

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

#### Python loc() function
The loc() function is label based data selecting method which means that we have to pass the name of the row or column which we want to select.

In [19]:
# selecting cars with brand 'Maruti' and Mileage > 25
display(data.loc[(data.Brand == 'Maruti') & (data.Mileage > 25)])

    Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [20]:
data.loc[(data.Brand == 'Maruti') & (data.Mileage > 25)]

    Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [ ]:
data.loc[2:4]

#### Python iloc() function
The iloc() function is an indexed-based selecting method which means that we have to pass an integer index in the method to select a specific row/column.

In [22]:
display(data.iloc[[0,1,2,3]])

      Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       28
1   Hyundai  2014       30000    Delhi       27
2      Tata  2011       60000   Mumbai       25
3  Mahindra  2015       25000    Delhi       26

### Get DataFrame Index
- We can access the DataFrame Index using the index attribute.

In [27]:
import pandas as pd

# create a dataframe
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 28, 32],
        'City': ['New York', 'London', 'Paris']}

df = pd.DataFrame(data)

df

# return index object
# print(df.index)

# return index values
print(df.index.values)

[0 1 2]

### Coding Test:
#### Default Index
- Create a DataFrame from the above dictionary and display it. (This will use the default index starting from 0.)
#### Setting a Custom Index
- Set the 'Name' column as the index of the DataFrame. Print the DataFrame with the new index.
#### Access a Row Using the New Index
- Print the row data for "Charlie" using .loc[].
#### Reset the Index Back to Default
- Use .reset_index() to bring the index back to default integers. Make sure the 'Name' column becomes a regular column again.
#### Create a DataFrame with a Range Index
- Create a new DataFrame where the index is a RangeIndex starting from 100 with a step of 10.
- Example: Index: [100, 110, 120, 130]

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Marks': [85, 92, 78, 90]
}
df = pd.DataFrame(data)
df