### Pandas DataFrame Manipulation

#### DataFrame manipulation in Pandas involves editing and modifying existing DataFrames. Some common DataFrame manipulation operations are:

1. Adding rows/columns
2. Removing rows/columns
3. Renaming rows/columns


### Add a New Column to a Pandas DataFrame
#### We can add a new column to an existing Pandas DataFrame by simply declaring a new list as a column.

In [ ]:
import pandas as pd

# define a dictionary containing student data
data = {'Name': ['John', 'Emma', 'Michael', 'Sophia'],
        'Height': [5.5, 6.0, 5.8, 5.3],
        'Qualification': ['BSc', 'BBA', 'MBA', 'BSc']}

# convert the dictionary into a DataFrame
df = pd.DataFrame(data)


# declare a new list (first step)
address = ['New York', 'London', 'Sydney','','sahil']
# # #
# # # # assign the list as a column

df['Address'] = address
# #
df

### Add a New Row to a Pandas DataFrame
#### Adding rows to a DataFrame is not quite as straightforward as adding columns in Pandas. We use the `.loc` property to add a new row to a Pandas DataFrame.

In [11]:
import pandas as pd

# define a dictionary containing student data
data = {'Name': ['John', 'Emma', 'Michael', 'Sophia'],
        'Height': [5.5, 6.0, 5.8, 5.3],
        'Qualification': ['BSc', 'BBA', 'MBA', 'BSc']}

# convert the dictionary into a DataFrame
df = pd.DataFrame(data)

#
df.loc[4] = ['Sahil', 5.0, 'LLM']
# # df
#
df

      Name  Height Qualification
0     John     5.5           BSc
1     Emma     6.0           BBA
2  Michael     5.8           MBA
3   Sophia     5.3           BSc

### Remove Rows/Columns from a Pandas DataFrame
#### We can use `drop()` to delete rows and columns from a DataFrame.

#### Remove Rows

In [16]:
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Felipe', 'Rita'],
        'Age': [25, 30, 35, 40, 22, 29],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Bogota', 'Banglore']}

df = pd.DataFrame(data)


# delete row with index 4
# df.drop(4, axis=0, inplace=True) # 2 main param , 1 optional


dropping_list = [1,3,5]
# # # # delete rows with index 1 and 3
df.drop(dropping_list, axis=0, inplace=True)
#

df

      Name  Age      City
0    Alice   25  New York
2  Charlie   35     Paris
4   Felipe   22    Bogota

#### Remove Columns

In [19]:
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Felipe', 'Rita'],
        'Age': [25, 30, 35, 40, 22, 29],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Bogota', 'Banglore']}

df = pd.DataFrame(data)



# Drop a single column
# col_list = ['Name', 'Age']
df.drop(columns='Name', inplace=True)
#
# df


df.drop('Name', axis=1, inplace=True)
#
# # Drop multiple columns
# df.drop(columns=['Name', 'Age'], inplace=True)
# df.drop(['column1', 'column2', 'column3'], axis=1, inplace=True)

df

   Age      City
0   25  New York
1   30    London
2   35     Paris
3   40     Tokyo
4   22    Bogota
5   29  Banglore

### Rename Labels in a DataFrame
#### We can rename columns in a Pandas DataFrame using the rename() function.

In [21]:
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'London', 'Paris', 'Tokyo']}

# predicate pushdown and projection pushdown

df = pd.DataFrame(data)

rename_dict = {'Name': 'First_Name',
               'Age': 'Age_In_Years',
               'City': 'City_Name'}

# display the original DataFrame

# rename columns 'Age' and 'Name'
df.rename(rename_dict, axis=1, inplace=True)


df

  First_Name  Age_In_Years City_Name
0      Alice            25  New York
1        Bob            30    London
2    Charlie            35     Paris
3      David            40     Tokyo

### Pandas Select

- Pandas select refers to the process of extracting specific portions of data from a DataFrame.
- Data selection involves choosing specific rows and columns based on labels, positions, or conditions.
- Pandas provides various methods, such as basic indexing, slicing, boolean indexing, and querying, to efficiently extract, filter, and transform data, enabling users to focus on relevant information for analysis and decision-making.

### Select Data Using Indexing and Slicing
#### In Pandas, we can use square brackets and their labels or positions to select the data we want.

In [ ]:
import pandas as pd

# create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 22, 27, 29],
    'Salary': [50000, 60000, 45000, 55000, 52000]
}

df = pd.DataFrame(data)




# selecting a single column
# name_df = df['Name']
#
# # this is my data frame selecting cols
# select_list = ['Age', 'Salary']
# #
# # # my new dataframe
# age_salary_df = df[select_list]

# selecting rows using slicing
selected_rows = df[1:4]


# name_df

selected_rows

### Pandas Reshape

- In Pandas, reshaping data refers to the process of converting a DataFrame from one format to another for better data visualization and analysis.
- Pandas provides multiple methods like `pivot()`, `pivot_table()`, `stack()`, `unstack()` and `melt()` to reshape data. We can choose the method based on our analysis requirement.

### Reshape Data Using pivot()
- In Pandas, the pivot() function reshapes data based on column values.
- It takes simple column-wise data as input, and groups the entries into a two-dimensional table.

In [ ]:
import pandas as pd


data = {
    'month': ['Jan','Jan','Feb','Feb'],
    'product' : ['Shoes','T-Shirt','Shoes','T-Shirt'],
    'sales' : [100,200,300,400]
}
df = pd.DataFrame(data)



# pivot the  DataFrame
# pivot_df = df.pivot(index='month', columns='product', values='sales')
pivot_df

# 0,Jan,Shoes,100
# 1,Jan,T-Shirt,200
# 2,Feb,Shoes,300
# 3,Feb,T-Shirt,400

### we have passed the parameters index, columns and values to the pivot function. Here,

- `index` specifies the column to be used as the index for the pivoted DataFrame
- `columns` specifies the column whose unique values will become the new column headers
- `values` specifies the column containing the values to be placed in the new columns

### Reshape Data Using pivot_table()
#### The `pivot_table()` function in Pandas is a way for reshaping and summarizing data in a DataFrame.
- It allows us to create a pivot table that aggregates and summarizes data based on the specified index, columns, and aggregation functions.

### Common Aggregation Functions for pivot_table()

You can use the following aggregate functions in `aggfunc`:

**Numeric Aggregations:**
- `'sum'` - Sum of values
- `'mean'` - Average of values
- `'median'` - Median of values
- `'min'` - Minimum value
- `'max'` - Maximum value
- `'std'` - Standard deviation
- `'var'` - Variance
- `'count'` - Count of non-null values
- `'size'` - Count of all values (including nulls)

**Custom Functions:**
- You can also pass custom functions like `np.mean`, `np.sum`, etc.
- Or pass a list of functions: `aggfunc=['sum', 'mean', 'count']`

**Examples:**

```python
# Sum of values
df.pivot_table(index='Category', values='Value', aggfunc='sum')

# Mean/Average
df.pivot_table(index='Category', values='Value', aggfunc='mean')

# Multiple aggregations
df.pivot_table(index='Category', values='Value', aggfunc=['sum', 'mean', 'count'])

# Min and Max
df.pivot_table(index='Category', values='Value', aggfunc='min')
df.pivot_table(index='Category', values='Value', aggfunc='max')
```

### Pandas Handling Duplicate Values

- In large datasets, we often encounter duplicate entries in tables. These duplicate entries can throw off our analysis and skew the results.
- Pandas provides several methods to find and remove duplicate entries in DataFrames.


### Find Duplicate Entries

- We can find duplicate entries in a DataFrame using the duplicated() method. It returns True if a row is duplicated and returns False otherwise.

In [ ]:
import pandas as pd

# create dataframe
data = {
    'Name': ['John', 'Anna', 'John', 'Anna', 'John'],
    'Age': [28, 24, 28, 24, 28],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

# df

# check for duplicate entries
# df.duplicated()

# check for duplicate entries in columns Name and Age
df.duplicated(subset=['Name', 'Age'])

### Remove Duplicate Entries
- We can remove duplicate entries in Pandas using the drop_duplicates() method.

In [ ]:
import pandas as pd

# create dataframe
data = {
    'Name': ['John', 'Anna', 'John', 'Anna', 'John'],
    'Age': [28, 24, 28, 24, 19],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)



# remove duplicates
df.drop_duplicates(inplace=True, keep='last') #keep=last
#
df

### Practice Test
1. Add a new column called "`DiscountedAmount`" that is OrderAmount minus 10% discount.
2. Remove the "`Name`" column from the DataFrame.
3. Drop duplicate entries based on the "`CustomerID`" column (keep the first occurrence only).

In [ ]:
import pandas as pd

data = {
    'CustomerID': [101, 102, 103, 101, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'David'],
    'OrderAmount': [250, 450, 300, 250, 500]
}

df = pd.DataFrame(data)

### Problem 1: Creating a DataFrame

Task: Create a DataFrame with the following data:


`data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [24, 30, 35, 40],
        'City': ['New York', 'Toronto', 'London', 'Sydney']}`

Goal: Display the created DataFrame.
### Problem 2: Basic DataFrame Operations

1. Display only the Name and City columns.
2. Select and print the rows where Age is greater than 30.

### Problem 3: Adding and Deleting Columns

1. Add a new column named Salary with values [70000, 80000, 120000, 95000].
2. Delete the City column.
3. Goal: Display the updated DataFrame.